version: 2.1
jobs:
  chrome_version:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/project
    steps:
      - run: google-chrome --product-version
  test_e2e:
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/project
    steps:
      - checkout
      # - run: npm install
      # - run: npm run start
      - run: cd site;yarn install
      # - run: cd site;yarn dev
      - run:
          name: set var
          command: echo "export CHROME_VER=`google-chrome --product-version`" >> $BASH_ENV
      - run: echo "$CHROME_VER"
      - run:
          name: Install Chrome
          command: |
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run: sudo npm install -g webdriver-manager
      - run: sudo webdriver-manager update --versions.chrome=79
      - run: cd site;yarn test:e2e
workflows:
  build:
    jobs:
      - chrome_version
      - test_e2e:
          filters:
            branches:
              only: master
