<template>
  <svg
    class="Icon Icon--nav-desktop"
    role="presentation"
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g
      fill="none"
      fill-rule="evenodd"
    >
      <path
        d="M0 0h24v24H0z"
        opacity=".628"
      />
      <rect
        fill="currentColor"
        x="4"
        y="5"
        width="16"
        height="2"
        rx="1"
      />
      <rect
        fill="currentColor"
        x="4"
        y="11"
        width="16"
        height="2"
        rx="1"
      />
      <rect
        fill="currentColor"
        x="4"
        y="17"
        width="16"
        height="2"
        rx="1"
      />
    </g>
  </svg>
</template>
